# Assignment 2: explanation datasets

## Fossil and electric driven boats
75 % of the 550 commercial cannal boats were driven electric in 2020 (Reuters, 2020). So 138 boats are still driven on fossil fuel and 412 are driven electric. In 2025 all the cannal boats has to be driven electric, this is in line with transition goals of the municipality of Amsterdam. From 2025 there will be a dieselmotor ban in the city centre, to improve the climate conditions. One canal boat sails 14 hours a day, therefore there was a priority to change the motor of the canal boats. 

## Support vessels Paralympic test event
When looked at the support vessels for previous Olympic open water swimming, for example the men's 10km marathon swimming of the 2021 Tokyo Olympics, it can be seen that the number of support vessels is 14 for 26 competitors, these vessels are a mix of motorboats and jetskis [(Highlights Olympic men's 10km open water swimming, Eurosport)](https://www.youtube.com/watch?v=1ZLWUkaq8po&ab_channel=Eurosport). The larger motorboats are the support vessels for the judges and organizers of the event, while the jetskis are support vessels for the lifeguards. Next to that, there are also multiple lifeguards on kayaks and paddleboards rowing along the swimmers as well. In contrast to other marathon swimming events, the Olympic race is a lap course instead of a point-to-point course. This also has an influence on the number of support vessels involved with the race, as the coaches of the swimmers are stationed on a pontoon along the course. In other circumstances, coaches and/or trainers of the swimmers kayak or paddle along with their swimmer as per the regulations of the relevant governing and regulatory bodies (FINA, WOWSA and/or BLDSA for example).

As the route of the proposed test event is a point-to-point with a section where the swimmers pass twice, we propose to have a combination of both situations previously explained with regard to coaches and trainers. We propose to place a pontoon in the middle of the Oosterdok area behind the Nemo pier, between it and the edge of Hanneke's Boom terrace. From this pontoon coaches or trainers can hand the swimmers drinks or nutrition and give instructions. While at the same time we propose to have a trainer or coach row along their swimmer in a kayak as well to provide extra security for the swimmers. In terms of other support vessels, we expect a similar number of participants for the proposed test events as the previously mentioned Olympic event. Therefore we think a similar amount of support vessels would be sufficient in addition to the extra kayaks and paddleboards for the trainers/coaches.
